### ISSUE TITLE
Suggestion - Adding Free Hudson Rock Cybercrime Intelligence Toolkit

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [rodanmaharjan/ThreatIntelligence#2]
Hi,

I would like to know if you're open to adding to your repository [Hudson Rock's free cybercrime intelligence toolkit](https://www.hudsonrock.com/threat-intelligence-cybercrime-tools).

The toolkit doesn't require registration and can indicate if an email address/domain, and much more was compromised in a global Infostealer malware attack. 

If yes, please kindly suggest the best way to do it. 
Thank you in advance.

**Comment by rodanmaharjan** [comment]
Please email me your proposal.
Regards!
